# Generated by Django 3.0.6 on 2020-05-29 15:48

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Striker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name of Striker')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Striker Address')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('age', models.IntegerField(blank=True, verbose_name='Age')),
                ('club', models.CharField(max_length=255, verbose_name='Current Club')),
                ('role', models.CharField(choices=[('unspecified', 'Unspecified'), ('pressing forward', 'Pressing Forward'), ('complete forward', 'Complete Forward'), ('advanced forward', 'Advanced Forward'), ('deep lying forward', 'Deep Lying Forward'), ('poacher', 'Poacher'), ('target man', 'Target Man'), ('false nine', 'False Nine'), ('trequartista', 'Trequartista')], default='unspecified', max_length=30, verbose_name='Role')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
