# Generated by Django 3.0.6 on 2020-06-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strikers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='striker',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nationality'),
        ),
    ]
