# Generated by Django 3.0.6 on 2020-06-15 11:21

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('strikers', '0002_striker_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='striker',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=255, null=True, verbose_name='Nationality'),
        ),
    ]
